<?php

namespace Container8cofpWd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UhzHUHeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UhzHUHe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UhzHUHe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ApprenantController::addApprenant' => ['privates', '.service_locator.TDqvbMT', 'get_ServiceLocator_TDqvbMTService', true],
            'App\\Controller\\GroupeController::list_apprenants' => ['privates', '.service_locator.CZN4nXf', 'get_ServiceLocator_CZN4nXfService', true],
            'App\\Controller\\GrpecompetencesController::list_competences' => ['privates', '.service_locator.vztKmTi', 'get_ServiceLocator_VztKmTiService', true],
            'App\\Controller\\GrptagsController::list_tags' => ['privates', '.service_locator.7oVUCyu', 'get_ServiceLocator_7oVUCyuService', true],
            'App\\Controller\\UserController::addUser' => ['privates', '.service_locator.g6R3j7C', 'get_ServiceLocator_G6R3j7CService', true],
            'App\\Controller\\UserController::putUser' => ['privates', '.service_locator.hkXCqrM', 'get_ServiceLocator_HkXCqrMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ApprenantController:addApprenant' => ['privates', '.service_locator.TDqvbMT', 'get_ServiceLocator_TDqvbMTService', true],
            'App\\Controller\\GroupeController:list_apprenants' => ['privates', '.service_locator.CZN4nXf', 'get_ServiceLocator_CZN4nXfService', true],
            'App\\Controller\\GrpecompetencesController:list_competences' => ['privates', '.service_locator.vztKmTi', 'get_ServiceLocator_VztKmTiService', true],
            'App\\Controller\\GrptagsController:list_tags' => ['privates', '.service_locator.7oVUCyu', 'get_ServiceLocator_7oVUCyuService', true],
            'App\\Controller\\UserController:addUser' => ['privates', '.service_locator.g6R3j7C', 'get_ServiceLocator_G6R3j7CService', true],
            'App\\Controller\\UserController:putUser' => ['privates', '.service_locator.hkXCqrM', 'get_ServiceLocator_HkXCqrMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ApprenantController::addApprenant' => '?',
            'App\\Controller\\GroupeController::list_apprenants' => '?',
            'App\\Controller\\GrpecompetencesController::list_competences' => '?',
            'App\\Controller\\GrptagsController::list_tags' => '?',
            'App\\Controller\\UserController::addUser' => '?',
            'App\\Controller\\UserController::putUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ApprenantController:addApprenant' => '?',
            'App\\Controller\\GroupeController:list_apprenants' => '?',
            'App\\Controller\\GrpecompetencesController:list_competences' => '?',
            'App\\Controller\\GrptagsController:list_tags' => '?',
            'App\\Controller\\UserController:addUser' => '?',
            'App\\Controller\\UserController:putUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
