<?php

namespace ContainerX9YobDv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserServicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\UserServices' shared autowired service.
     *
     * @return \App\Services\UserServices
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/UserServices.php';

        $a = ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService'));

        return $container->privates['App\\Services\\UserServices'] = new \App\Services\UserServices($a, ($container->services['serializer'] ?? $container->getSerializerService()), ($container->services['validator'] ?? $container->getValidatorService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), $a);
    }
}
