<?php

namespace ContainerX6FSlfp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8dFfNdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8d_FfNd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8d_FfNd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'service' => ['privates', 'App\\Services\\UserServices', 'getUserServicesService', true],
            'validator' => ['services', 'validator', 'getValidatorService', false],
        ], [
            'encoder' => '?',
            'manager' => '?',
            'repo' => 'App\\Repository\\UserRepository',
            'serializer' => '?',
            'service' => 'App\\Services\\UserServices',
            'validator' => '?',
        ]);
    }
}
