<?php

namespace ContainerX6FSlfp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGrpecompetencesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GrpecompetencesController' shared autowired service.
     *
     * @return \App\Controller\GrpecompetencesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GrpecompetencesController.php';

        $container->services['App\\Controller\\GrpecompetencesController'] = $instance = new \App\Controller\GrpecompetencesController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\GrpecompetencesController', $container));

        return $instance;
    }
}
