<?php

namespace ContainerBhuwCoa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CZN4nXfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CZN4nXf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CZN4nXf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo_apprenant' => ['privates', 'App\\Repository\\GroupeRepository', 'getGroupeRepositoryService', true],
        ], [
            'repo_apprenant' => 'App\\Repository\\GroupeRepository',
        ]);
    }
}
