<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'DoctrineNamespaceCacheKey%5B%5D' => 0,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23setContainer%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23setContainer%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getParameter%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getParameter%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getSubscribedServices%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getSubscribedServices%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23has%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23has%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23get%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23get%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23generateUrl%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23generateUrl%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23forward%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23forward%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirect%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirect%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirectToRoute%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirectToRoute%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23json%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23json%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23file%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23file%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addFlash%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addFlash%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isGranted%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isGranted%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23denyAccessUnlessGranted%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23denyAccessUnlessGranted%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23renderView%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23renderView%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23render%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23render%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23stream%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23stream%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createNotFoundException%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createNotFoundException%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createAccessDeniedException%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createAccessDeniedException%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createForm%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createForm%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createFormBuilder%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createFormBuilder%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getDoctrine%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getDoctrine%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getUser%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getUser%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isCsrfTokenValid%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isCsrfTokenValid%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23dispatchMessage%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23dispatchMessage%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addLink%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addLink%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%24container%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%24container%5D%5B1%5D' => 2,
'%5BApp%5CController%5CApprenantController%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CController%5CApprenantController%5D%5B1%5D' => 2,
'%5BApp%5CController%5CApprenantController%23addApprenant%5D%5B1%5D' => 3,
'%5B%5BC%5DApp%5CController%5CApprenantController%23addApprenant%5D%5B1%5D' => 2,
'%5BApp%5CController%5CUserController%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CController%5CUserController%5D%5B1%5D' => 2,
'%5BApp%5CController%5CUserController%23addUser%5D%5B1%5D' => 4,
'%5B%5BC%5DApp%5CController%5CUserController%23addUser%5D%5B1%5D' => 2,
'%5BApp%5CController%5CUserController%23putUser%5D%5B1%5D' => 5,
'%5B%5BC%5DApp%5CController%5CUserController%23putUser%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAdmin%5D%5B1%5D' => 6,
'%5B%5BC%5DApp%5CEntity%5CAdmin%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAdmin%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CAdmin%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getUsername%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getUsername%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setUsername%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setUsername%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getRoles%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getRoles%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setRoles%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setRoles%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getPlainPassword%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getPlainPassword%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setPlainPassword%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setPlainPassword%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getPassword%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getPassword%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setPassword%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setPassword%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getSalt%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getSalt%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23eraseCredentials%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23eraseCredentials%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getProfil%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getProfil%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setProfil%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setProfil%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getPrenom%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getPrenom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setPrenom%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setPrenom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getNom%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getNom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setNom%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setNom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getTelephone%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getTelephone%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setTelephone%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setTelephone%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getEmail%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getEmail%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setEmail%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setEmail%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getArchive%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getArchive%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setArchive%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setArchive%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getAvatar%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getAvatar%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setAvatar%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setAvatar%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CAdmin%24id%5D%5B1%5D' => 7,
'%5B%5BC%5DApp%5CEntity%5CAdmin%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24username%5D%5B1%5D' => 8,
'%5B%5BC%5DApp%5CEntity%5CUser%24username%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24roles%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%24roles%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24password%5D%5B1%5D' => 9,
'%5B%5BC%5DApp%5CEntity%5CUser%24password%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24plainPassword%5D%5B1%5D' => 10,
'%5B%5BC%5DApp%5CEntity%5CUser%24plainPassword%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24profil%5D%5B1%5D' => 11,
'%5B%5BC%5DApp%5CEntity%5CUser%24profil%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24prenom%5D%5B1%5D' => 12,
'%5B%5BC%5DApp%5CEntity%5CUser%24prenom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24nom%5D%5B1%5D' => 12,
'%5B%5BC%5DApp%5CEntity%5CUser%24nom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24telephone%5D%5B1%5D' => 12,
'%5B%5BC%5DApp%5CEntity%5CUser%24telephone%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24email%5D%5B1%5D' => 12,
'%5B%5BC%5DApp%5CEntity%5CUser%24email%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%5D%5B1%5D' => 13,
'%5B%5BC%5DApp%5CEntity%5CApprenant%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CApprenant%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%23getNiveau%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CApprenant%23getNiveau%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%23setNiveau%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CApprenant%23setNiveau%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%23getAdresse%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CApprenant%23getAdresse%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%23setAdresse%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CApprenant%23setAdresse%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%23getStatut%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CApprenant%23getStatut%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%23setStatut%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CApprenant%23setStatut%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%23getGroupe%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CApprenant%23getGroupe%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%23setGroupe%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CApprenant%23setGroupe%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%24id%5D%5B1%5D' => 7,
'%5B%5BC%5DApp%5CEntity%5CApprenant%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%24niveau%5D%5B1%5D' => 14,
'%5B%5BC%5DApp%5CEntity%5CApprenant%24niveau%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%24adresse%5D%5B1%5D' => 14,
'%5B%5BC%5DApp%5CEntity%5CApprenant%24adresse%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%24statut%5D%5B1%5D' => 14,
'%5B%5BC%5DApp%5CEntity%5CApprenant%24statut%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%24groupe%5D%5B1%5D' => 15,
'%5B%5BC%5DApp%5CEntity%5CApprenant%24groupe%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CCM%5D%5B1%5D' => 16,
'%5B%5BC%5DApp%5CEntity%5CCM%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CCM%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CCM%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CCM%24id%5D%5B1%5D' => 7,
'%5B%5BC%5DApp%5CEntity%5CCM%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CFormateur%5D%5B1%5D' => 17,
'%5B%5BC%5DApp%5CEntity%5CFormateur%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CFormateur%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CFormateur%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CFormateur%24id%5D%5B1%5D' => 7,
'%5B%5BC%5DApp%5CEntity%5CFormateur%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%5D%5B1%5D' => 18,
'%5B%5BC%5DApp%5CEntity%5CProfil%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23__construct%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23getLibelle%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23getLibelle%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23setLibelle%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23setLibelle%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23getUser%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23getUser%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23addUser%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23addUser%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23removeUser%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23removeUser%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23getArchive%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23getArchive%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23setArchive%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23setArchive%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%24id%5D%5B1%5D' => 19,
'%5B%5BC%5DApp%5CEntity%5CProfil%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%24libelle%5D%5B1%5D' => 20,
'%5B%5BC%5DApp%5CEntity%5CProfil%24libelle%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%24user%5D%5B1%5D' => 21,
'%5B%5BC%5DApp%5CEntity%5CProfil%24user%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%24archive%5D%5B1%5D' => 22,
'%5B%5BC%5DApp%5CEntity%5CProfil%24archive%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%5D%5B1%5D' => 23,
'%5B%5BC%5DApp%5CEntity%5CUser%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24id%5D%5B1%5D' => 7,
'%5B%5BC%5DApp%5CEntity%5CUser%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24archive%5D%5B1%5D' => 24,
'%5B%5BC%5DApp%5CEntity%5CUser%24archive%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24avatar%5D%5B1%5D' => 25,
'%5B%5BC%5DApp%5CEntity%5CUser%24avatar%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23setContainer%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23setContainer%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainAction%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainAction%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLitePlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLitePlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLServerPlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLServerPlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOtherPlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOtherPlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOraclePlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOraclePlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%24container%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%24container%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23addInsert%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23addInsert%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInsertSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInsertSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getResultSetMapping%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getResultSetMapping%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23exists%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23exists%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCacheRegion%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCacheRegion%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getEntityHydrator%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getEntityHydrator%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeEntityCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeEntityCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeJoinedAssociations%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeJoinedAssociations%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getHash%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getHash%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23load%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23load%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadAll%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadAll%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadById%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadById%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23count%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23count%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadCriteria%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadCriteria%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23lock%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23lock%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23refresh%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23refresh%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23buildCollectionCacheKey%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23buildCollectionCacheKey%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionComplete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionComplete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionRolledBack%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionRolledBack%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24uow%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24uow%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24metadataFactory%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24metadataFactory%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24persister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24persister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24class%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24class%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24queuedCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24queuedCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24region%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24region%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampRegion%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampRegion%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampKey%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampKey%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24hydrator%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24hydrator%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cacheLogger%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cacheLogger%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24regionName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24regionName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24joinedAssociations%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24joinedAssociations%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23getEntityHydrator%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23getEntityHydrator%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23storeEntityCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23storeEntityCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23getCacheRegion%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23getCacheRegion%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getResultSetMapping%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getResultSetMapping%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInsertSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInsertSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23addInsert%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23addInsert%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23count%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23count%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23load%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23load%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadById%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadById%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23refresh%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23refresh%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadCriteria%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadCriteria%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadAll%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadAll%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23lock%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23lock%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23exists%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23exists%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23updateCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23updateCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23prepareInsertData%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23prepareInsertData%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectJoinColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectJoinColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getResultSetMapping%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getResultSetMapping%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23addInsert%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23addInsert%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23assignDefaultVersionValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23assignDefaultVersionValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23fetchVersionValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23fetchVersionValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23extractIdentifierTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23extractIdentifierTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23updateTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23updateTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23deleteJoinTableRecords%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23deleteJoinTableRecords%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareUpdateData%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareUpdateData%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23load%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23load%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadById%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadById%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23refresh%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23refresh%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23count%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23count%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCriteria%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCriteria%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadAll%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadAll%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadArrayFromStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadArrayFromStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCollectionFromStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCollectionFromStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOrderBySQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOrderBySQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnsSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnsSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnAssociationSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnAssociationSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectManyToManyJoinSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectManyToManyJoinSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertColumnList%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertColumnList%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLTableAlias%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLTableAlias%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23lock%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23lock%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getLockTablesSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getLockTablesSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandToManyParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandToManyParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getValues%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getValues%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getIndividualValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getIndividualValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23exists%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23exists%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getJoinSQLForJoinColumns%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getJoinSQLForJoinColumns%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLColumnAlias%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLColumnAlias%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23generateFilterConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23generateFilterConditionSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23switchPersisterContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23switchPersisterContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassIdentifiersTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassIdentifiersTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24class%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24class%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24conn%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24conn%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24platform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24platform%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24em%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24em%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24queuedInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24queuedInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24columnTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24columnTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quotedColumns%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quotedColumns%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quoteStrategy%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quoteStrategy%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24currentPersisterContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24currentPersisterContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareInsertData%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareInsertData%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24comparisonMap%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24comparisonMap%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24insertSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24insertSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24identifierFlattener%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24identifierFlattener%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24limitsHandlingContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24limitsHandlingContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24noLimitsContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24noLimitsContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24class%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24class%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24rsm%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24rsm%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectColumnListSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectColumnListSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectJoinSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectJoinSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlAliasCounter%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlAliasCounter%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlTableAliases%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlTableAliases%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24handlesLimits%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24handlesLimits%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getVersionedClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getVersionedClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getLockTablesSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getLockTablesSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectColumnsSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectColumnsSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getInsertColumnList%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getInsertColumnList%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23assignDefaultVersionValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23assignDefaultVersionValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getJoinSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getJoinSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24owningTableMap%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24owningTableMap%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24quotedTableMap%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24quotedTableMap%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectColumnsSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectColumnsSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getInsertColumnList%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getInsertColumnList%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSQLTableAlias%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSQLTableAlias%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionDiscriminatorValueSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionDiscriminatorValueSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23generateFilterConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23generateFilterConditionSQL%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__construct%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23redirectAction%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23redirectAction%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23urlRedirectAction%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23urlRedirectAction%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__invoke%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__invoke%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23parseQuery%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23parseQuery%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24router%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24router%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpPort%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpPort%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpsPort%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpsPort%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__construct%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23templateAction%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23templateAction%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__invoke%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__invoke%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%24twig%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%24twig%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23__construct%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23supports%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23supports%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23resolve%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23resolve%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%24tokenStorage%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%24tokenStorage%5D%5B1%5D' => 2,

], [

0 => 'N;',
1 => [],
2 => 1612645443,
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    'api/apprenants/',
                ],
                'name' => [
                    'add_apprenant',
                ],
                'defaults' => [
                    [
                        '__controller' => 'App\\Controller\\ApprenantController::addApprenant',
                        '__api_resource_class' => 'Apprenant',
                        '__api_collection_operation_name' => 'add_apprenant',
                    ],
                ],
                'methods' => [
                    [
                        'POST',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/admin/users',
                ],
                'name' => [
                    'add_user',
                ],
                'defaults' => [
                    [
                        '__controller' => 'App\\Controller\\UserController::addUser',
                        '__api_resource_class' => 'App\\Entity\\User',
                        '__api_collection_operation_name' => 'add_user',
                    ],
                ],
                'methods' => [
                    [
                        'POST',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/api/admin/users/{id}',
                ],
                'name' => [
                    'update_user',
                ],
                'defaults' => [
                    [
                        '__controller' => 'App\\Controller\\UserController::putUser',
                        '__api_resource_class' => 'App\\Entity\\User',
                        '__api_item_operation_name' => 'put',
                    ],
                ],
                'methods' => [
                    [
                        'PUT',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'repositoryClass' => [
                    1 => 'App\\Repository\\AdminRepository',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Id'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Id')),
            clone ($p['Doctrine\\ORM\\Mapping\\GeneratedValue'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\GeneratedValue')),
            clone ($p['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    2 => 'integer',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
        ],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Validator\\Constraints\\NotBlank'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotBlank')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'length' => [
                    180,
                ],
                'unique' => [
                    true,
                ],
                'groups' => [
                    1 => [
                        'Default',
                    ],
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    2 => [
                        'users:read',
                        'users:write',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
        ],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [],
        [
            $o[0],
        ],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Serializer\\Annotation\\SerializedName'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\SerializedName')),
        ],
        null,
        [
            'Symfony\\Component\\Serializer\\Annotation\\SerializedName' => [
                'serializedName' => [
                    'password',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ManyToOne'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOne')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'targetEntity' => [
                    'App\\Entity\\Profil',
                ],
                'inversedBy' => [
                    'user',
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    1 => [
                        'users:read',
                        'users:write',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
12 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'length' => [
                    255,
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    1 => [
                        'users:read',
                        'users:write',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
13 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'collectionOperations' => [
                    [
                        'add_apprenant' => [
                            'security' => 'is_granted(\'ROLE_Admin\')',
                            'security_message' => 'Seul l\'admin peut ajouter cette ressource',
                            'method' => 'POST',
                            'path' => '/apprenants',
                        ],
                        'GET' => [
                            'security' => 'is_granted(\'ROLE_Admin\') or is_granted(\'ROLE_Formateur\') or is_granted(\'ROLE_CM\') ',
                            'security_message' => 'Seul l\'admin peut ajouter cette ressource',
                            'method' => 'GET',
                            'path' => '/apprenants',
                        ],
                    ],
                ],
                'itemOperations' => [
                    [
                        'get' => [
                            'method' => 'GET',
                            'path' => 'apprenants/{id}',
                            'requirements' => [
                                'id' => '\\d+',
                            ],
                        ],
                        'put' => [
                            'path' => 'apprenants/{id}',
                        ],
                    ],
                ],
                'attributes' => [
                    [
                        'security' => 'is_granted(\'ROLE_User\')',
                        'security_message' => 'Vous n\'avez pas acces à cette ressource',
                    ],
                ],
                'repositoryClass' => [
                    1 => 'App\\Repository\\ApprenantRepository',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
14 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'length' => [
                    255,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
15 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\ManyToOne'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOne')),
        ],
        null,
        [
            'stdClass' => [
                'targetEntity' => [
                    'App\\Entity\\Groupe',
                ],
                'inversedBy' => [
                    'apprenants',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
16 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'repositoryClass' => [
                    1 => 'App\\Repository\\CMRepository',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
17 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'attributes' => [
                    [
                        'security' => 'is_granted(\'ROLE_Admin\')',
                        'security_message' => 'Seul le formateur a access à cette ressource',
                    ],
                ],
                'repositoryClass' => [
                    1 => 'App\\Repository\\FormateurRepository',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
18 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'collectionOperations' => [
                    [
                        'GET',
                        'POST',
                    ],
                ],
                'itemOperations' => [
                    [
                        'GET',
                        'PUT',
                        'DELETE',
                    ],
                ],
                'attributes' => [
                    [
                        'security' => 'is_granted(\'ROLE_Admin\')',
                        'security_message' => 'Seul l\'admin a acces à cette ressource',
                        'route_prefix' => '/admin',
                        'normalization_context' => [
                            'groups' => [
                                'profil:read',
                            ],
                        ],
                        'denormalization_context' => [
                            'groups' => [
                                'profil:write',
                            ],
                        ],
                    ],
                ],
                'repositoryClass' => [
                    1 => 'App\\Repository\\ProfilRepository',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
19 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Id'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Id')),
            clone ($p['Doctrine\\ORM\\Mapping\\GeneratedValue'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\GeneratedValue')),
            clone ($p['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    2 => 'integer',
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    3 => [
                        'users:read',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
            $o[3],
        ],
        []
    );
},
20 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Validator\\Constraints\\NotBlank'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotBlank')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'length' => [
                    255,
                ],
                'message' => [
                    1 => 'Ne dois pas etre vide !!!',
                ],
                'groups' => [
                    1 => [
                        'Default',
                    ],
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    2 => [
                        'profil:read',
                        'profil:write',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
        ],
        []
    );
},
21 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\OneToMany'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToMany')),
            clone ($p['ApiPlatform\\Core\\Annotation\\ApiSubresource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiSubresource')),
        ],
        null,
        [
            'stdClass' => [
                'mappedBy' => [
                    'profil',
                ],
                'targetEntity' => [
                    'App\\Entity\\User',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
22 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'boolean',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
23 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
            clone ($p['Doctrine\\ORM\\Mapping\\InheritanceType'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\InheritanceType')),
            clone ($p['Doctrine\\ORM\\Mapping\\DiscriminatorColumn'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\DiscriminatorColumn')),
            clone ($p['Doctrine\\ORM\\Mapping\\DiscriminatorMap'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\DiscriminatorMap')),
            clone ($p['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
        ],
        null,
        [
            'stdClass' => [
                'repositoryClass' => [
                    'App\\Repository\\UserRepository',
                ],
                'value' => [
                    1 => 'JOINED',
                    3 => [
                        'user' => 'User',
                        'apprenant' => 'Apprenant',
                        'formateur' => 'Formateur',
                        'admin' => 'Admin',
                        'cm' => 'CM',
                    ],
                ],
                'name' => [
                    2 => 'type',
                ],
                'type' => [
                    2 => 'string',
                ],
                'collectionOperations' => [
                    4 => [
                        'add_user' => [
                            'method' => 'POST',
                            'path' => '',
                            'deserialize' => false,
                        ],
                        'GET' => [
                            'method' => 'GET',
                            'path' => '',
                        ],
                    ],
                ],
                'itemOperations' => [
                    4 => [
                        'PUT',
                        'DELETE',
                        'get' => [
                            'method' => 'GET',
                            'path' => '/{id}',
                            'requirements' => [
                                'id' => '\\d+',
                            ],
                        ],
                        'put' => [
                            'method' => 'PUT',
                            'path' => '/{id}',
                            'requirements' => [
                                'id' => '\\d+',
                            ],
                        ],
                    ],
                ],
                'attributes' => [
                    4 => [
                        'security' => 'is_granted(\'ROLE_Admin\')',
                        'security_message' => 'Seul l\'admin a acces à cette ressource',
                        'route_prefix' => '/admin/users/',
                        'normalization_context' => [
                            'groups' => [
                                'users:read',
                            ],
                        ],
                        'denormalization_context' => [
                            'groups' => [
                                'users:write',
                            ],
                        ],
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
            $o[3],
            $o[4],
        ],
        []
    );
},
24 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'boolean',
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    1 => [
                        'users:read',
                        'users:write',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
25 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'blob',
                ],
                'nullable' => [
                    true,
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    1 => [
                        'users:read',
                        'users:write',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},

]];
