<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX9YobDv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX9YobDv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX9YobDv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX9YobDv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX9YobDv\App_KernelDevDebugContainer([
    'container.build_hash' => 'X9YobDv',
    'container.build_id' => '2d49b2e4',
    'container.build_time' => 1612654177,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX9YobDv');
