<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZN1mQGI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZN1mQGI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZN1mQGI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZN1mQGI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZN1mQGI\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZN1mQGI',
    'container.build_id' => 'e4252521',
    'container.build_time' => 1612645895,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZN1mQGI');
