<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAyZaeJH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAyZaeJH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAyZaeJH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAyZaeJH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAyZaeJH\App_KernelDevDebugContainer([
    'container.build_hash' => 'AyZaeJH',
    'container.build_id' => 'bc814d38',
    'container.build_time' => 1613434498,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAyZaeJH');
